export const jwtConstants = {
  ACCESS_TOKEN:
    'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP',
  REFRESH_TOKEN:
    'DO NOT USE THIS VALUE. INSTEAD, CREATE A COMPLEX SECRET AND KEEP',
};
